spring.application.name=reactive-runtime
spring.ai.bedrock.aws.region=eu-west-1
spring.ai.bedrock.converse.chat.model=eu.anthropic.claude-sonnet-4-20250514-v1:0
agentcore.throttle.invocations-limit=2
agentcore.throttle.ping-limit=3